apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-devops-foundation-deploy
  labels:
    app: ms-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-spring
  template:
    metadata:
      labels:
        app: ms-spring
    spec:
      containers:
      - name: ms-spring
        image: dargor980/lab-ms-spring:latest
        ports:
        - containerPort: 8080

